on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH action
        uses: appleboy/ssh-action@1.0.0
        with:
          host: jnsl.tk
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script : |
            cd shrtr_app
            touch hello.txt
